<?php

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form -> prepare(); //where to go after submit button is hit. But it is giving error
$form->setAttribute('action', $this->url('csn_user/default', array('controller' => 'user', 'action' => 'create')));
$form ->setAttribute('method', 'post');


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo "<br />";
echo $this->formRow($form->get('artist'));
echo "<br />";
echo $this->formSubmit($form->get('submit'));
echo "<br />";
echo $this->form()->closeTag();