<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php /*echo $this->url('csn-user', array('controller' => 'user', 'action' => 'create'));*/?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($rowset as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->title);?></td>
            <td><?php echo $this->escapeHtml($row->artist);?></td>
            <td>
                <a href="<?php echo $this->url('csn_user/default',
                    array('controller' => 'user', 'action'=>'update', 'id' => $row->id));?>">Edit</a>
                <a href="<?php echo $this->url('csn_user/default',
                    array('controller' => 'user', 'action'=>'delete', 'id' => $row->id));?>" onclick="return confirm('Do you rely want to delete the record?')">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>